task and tag models added. user model updated.
NickelGit/TaskManagerPy pull request #6
Opened 2023-06-20 18:17 UTC by NickelGit

2023-06-21 10:47 UTC, aleksandr-semenov-dbp requested changes

2023-06-21 10:47 UTC, aleksandr-semenov-dbp commented on task_manager/main/models/tag.py
> +    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
В принципе здесь не очень важна секьюрность, поэтому стандартного id который Джанго добавляет в модели вполне достаточно. Если хочется делать uuid - надо по крайней мере добавить primary_key=True, возможно еще что-то, стоит погуглить. Для целей упражнений я бы не заморачивался и оставил здесь один title

2023-06-21 10:52 UTC, NickelGit commented on task_manager/main/models/tag.py
> +    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
А, ок, спасибо! 
Я не хотел ставить его primary_key, просто в задаче отдельно было указано что нужен будет какой то "уникальный идентификатор".
```
урок 0. Введение. Постановка задачи

"...
Тег представляет собой модель с полями:

* заголовок;
* уникальный идентификатор;
..."
```

подумал что раз явно прописано только в этой модели, то возможно в дальнейшем понадобится что то отдельное от обычного ID. И решил воспользоваться готовым решением)

Сегодня удалю, большое спасибо!

2023-06-21 16:47 UTC, NickelGit commented on task_manager/main/models/tag.py
> +    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
[исправленно](https://github.com/NickelGit/TaskManagerPy/pull/6/commits/e4b91aac2c5be4400b107782b78d0fea12714c88)

2023-06-22 06:21 UTC, aleksandr-semenov-dbp approved these changes

2023-06-22 06:32 UTC, merged